services:
  db:
    image: postgres:16-alpine
    container_name: portfolio_db
    restart: unless-stopped
    env_file:
      - app/.env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portfolio"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: portfolio_app
    restart: unless-stopped
    env_file:
      - app/.env
    environment:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    # Use the production server command defined in the Dockerfile

volumes:
  db_data: