services:
  db:
    image: postgres:16-alpine
    container_name: portfolio_db
    restart: unless-stopped
    env_file:
      - app/.env
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portfolio"]
      interval: 5s
      timeout: 5s
      retries: 20

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: portfolio_app
    restart: unless-stopped
    env_file:
      - app/.env
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: "1"
    ports:
      - "3001:3000"
    volumes:
      - ./app:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "npx prisma generate && npx prisma db push && npm run dev -- -H 0.0.0.0 -p 3000"

volumes:
  db_data: