import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./(pages)/styles.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/icons/favicon/ms.png',
    shortcut: '/icons/favicon/ms.png',
    apple: '/icons/favicon/ms.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <style dangerouslySetInnerHTML={{
          __html: `
            /* Critical inline styles to prevent FOUC */
            html, body { 
              background: #ffffff !important; 
              color: #1f2937 !important; 
              font-family: Inter, system-ui, -apple-system, sans-serif !important;
              margin: 0 !important;
              padding: 0 !important;
            }
            .three-loading-screen { 
              position: fixed !important; 
              top: 0 !important; 
              left: 0 !important; 
              width: 100vw !important; 
              height: 100vh !important; 
              background: linear-gradient(135deg, #ffffff 0%, #fdf2f8 50%, #ffffff 100%) !important; 
              z-index: 9999 !important; 
            }
          `
        }} />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
